export const PAGE_ITEMS = 7;
export const TYPE_DEVICE = [
  "Pc",
  "Camera",
  "Component",
  "Headphone",
  "Keyboard",
  "Laptop",
  "Monitor",
  "Mouse",
];
export const TECH_SPECIFICATION: string[] = [
  "CPU",
  "RAM",
  "storage",
  "graphicCard",
  "display",
  "ports",
  "audio",
  "keyboard",
  "cardReader",
  "wifiStandard",
  "bluetooth",
  "webcam",
  "operatingSystem",
  "battery",
  "weight",
  "color",
  "dimensions",
];

export const BRANDS = [
  "Dell",
  "ASUS",
  "ACER",
  "MSI",
  "Lenovo",
  "Ezviz",
  "TP-Link",
  "Xiaomi",
  "Samsung",
  "Gigabyte",
  "ViewSonic",
  "Logitech",
  "Razer",
  "DareU",
  "Akko",
  "E-DRA",
  "Rapoo",
  "Corsair",
  "HyperX",
  "Apple",
  "Sony",
];

export const ORDER_TAB = [
  { titile: "Tất cả" },
  { titile: "Chưa chấp nhận" },
  { titile: "Đã chấp nhận" },
  { titile: "Đang giao" },
  { titile: "Đã hoàn thành" },
  { titile: "Đã hủy" },
];
